### ISSUE TITLE
Auto login if not logout last time

### ISSUE THREAD

**Issue by Steven-Chan** [skygear-demo/skygear-react-google-login#5]
I think it would be good to demonstrate how to implement auto login, since this is required in most application.

### Auto login flow

1. In `componentDidMount` of `App`, check `skygear.auth.accessToken`.
1. If access token exists, call `skygear.auth.whoami()` and `skygear.auth.getOAuthProviderProfiles()`.
1. If access token does not exist, just display `not yet signed in` like the current one.
1. If both `skygear.auth.whoami()` and `skygear.auth.getOAuthProviderProfiles()` returns successful results, display user and profile data, the displayed information should look the same as that when a user successfully logged in with the `Login with Google` button.
1. If either of the call `skygear.auth.whoami()` or `skygear.auth.getOAuthProviderProfiles()` get error, call `skygear.auth.logout()` for the user.

### Code needs to be changed

With the current implementation, if you call `skygear.auth.accessToken` in `componentDidMount` of `App`, it would always return `null`.

The reason is `skygear.config` in `index.js` is asynchronous, the easiest fix is to render the react app AFTER `skygear.config` is finished, in this way you can always assume `skygear` is ready to use in your components.

**Comment by bryanchun** [comment]
Thank you for your feedback! I have pushed fixes and changes onto my fork so please have a look of the new commits (or I can do a pull request). Most are done and pending for review, but I have some questions on this issue and so this issue remains.

I don't know how to "render the react app AFTER `skygear.config` is finished". I tried to put all the pieces together and then react gives me this error:

![screenshot 2018-07-07 00 20 52](https://user-images.githubusercontent.com/22416129/42389522-a3377154-817b-11e8-8fa1-66edaf27223e.png)

which I believe is an issue of the async `skygear.config` not getting ready yet for `componentDidMount`. [Searching on stackoverflow](https://stackoverflow.com/questions/43946738/webpack-compile-error-typeerror-webpack-imported-module-1-is-not-a-funct) gives irrelevant answers. Hence currently, the block of code is written but commented out.

I would be very helpful if you can show me your idea of "making sure the async call is settled before the coming `componentDidMount`" or other related ideas. Thank you very much.

**Comment by Steven-Chan** [comment]
Try this:
```
skygear
  .config(...)
  .then(() => {
    ReactDOM.render(...);
  });
```
